mode: debug
name: http
log_level: info
log_path: log
log_level_addr: :4241
log_level_pattern: /log/level

app:
  domain: http://127.0.0.1:8080
  static_root_path: static
  runtime_root_path: runtime/
  image_allow_ext: .jpg,.jpeg,.png
  image_max_size: 5
  heartbeat: 1000
  jwt_time: 7200
  jwt_secret: social-key

http:
  addr: :8080

mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  dbname: blog
  max_open_conns: 100
  max_idle_conns: 10
  # seconds
  max_life_time: 24*60*60

redis:
  addr: 127.0.0.1
  port: 6379
  password:
  pool_size: 5
  min_idle_conn: 2
