#!/bin/bash

MSG=`awk '{printf("%s",$0)}' $1`

# Skip detection for Merge or Rebase
if [[ $MSG =~ ^(Merge|Rebase).+.* ]]
  then
    exit 0
fi

if [ ${#MSG} -lt 10 ]
  then
    echo "-------------------------------------------------------------------"
    echo "Commit failed! Reason: Commit message length cannot be less than 10, current length: ${#MSG}"
    echo "Correct example: feat: #API-001 Add member list API"
    echo "Commit message: ${MSG}"
    echo "-------------------------------------------------------------------"
    exit 1
fi

if [[ $MSG =~ ^feat:[[:blank:]].* ]] ||
   [[ $MSG =~ ^feat\(.*\):[[:blank:]].* ]] ||
   [[ $MSG =~ ^fix:[[:blank:]].* ]] ||
   [[ $MSG =~ ^fix\(.*\):[[:blank:]].* ]] ||
   [[ $MSG =~ ^style:[[:blank:]].* ]] ||
   [[ $MSG =~ ^style\(.*\):[[:blank:]].* ]] ||
   [[ $MSG =~ ^refactor:[[:blank:]].* ]] ||
   [[ $MSG =~ ^refactor\(.*\):[[:blank:]].* ]] ||
   [[ $MSG =~ ^docs:[[:blank:]].* ]] ||
   [[ $MSG =~ ^docs\(.*\):[[:blank:]].* ]] ||
   [[ $MSG =~ ^test:[[:blank:]].* ]] ||
   [[ $MSG =~ ^test\(.*\):[[:blank:]].* ]] ||
   [[ $MSG =~ ^chore:[[:blank:]].* ]] ||
   [[ $MSG =~ ^chore\(.*\):[[:blank:]].* ]] ||
   [[ $MSG =~ ^revert:[[:blank:]]feat:[[:blank:]].* ]] ||
   [[ $MSG =~ ^revert:[[:blank:]]feat\(.*\):[[:blank:]].* ]] ||
   [[ $MSG =~ ^revert:[[:blank:]]fix:[[:blank:]].* ]] ||
   [[ $MSG =~ ^revert:[[:blank:]]fix\(.*\):[[:blank:]].* ]] ||
   [[ $MSG =~ ^revert:[[:blank:]]style:[[:blank:]].* ]] ||
   [[ $MSG =~ ^revert:[[:blank:]]style\(.*\):[[:blank:]].* ]] ||
   [[ $MSG =~ ^revert:[[:blank:]]refactor:[[:blank:]].* ]] ||
   [[ $MSG =~ ^revert:[[:blank:]]refactor\(.*\):[[:blank:]].* ]] ||
   [[ $MSG =~ ^revert:[[:blank:]]docs:[[:blank:]].* ]] ||
   [[ $MSG =~ ^revert:[[:blank:]]docs\(.*\):[[:blank:]].* ]] ||
   [[ $MSG =~ ^revert:[[:blank:]]test:[[:blank:]].* ]] ||
   [[ $MSG =~ ^revert:[[:blank:]]test\(.*\):[[:blank:]].* ]] ||
   [[ $MSG =~ ^revert:[[:blank:]]chore:[[:blank:]].* ]] ||
   [[ $MSG =~ ^revert:[[:blank:]]chore\(.*\):[[:blank:]].* ]]
  then
    :
  else
    echo "-------------------------------------------------------------------"
    echo "Commit failed! Reason: Commit message does not conform to Commit Message specification"
    echo "Correct example: feat: #API-001 Add member list API"
    echo "Commit message: ${MSG}"
    echo "-------------------------------------------------------------------"
    exit 1
fi

if [[ $MSG =~ ^.+#.+-.* ]]
 then
   :
 else
   echo "-------------------------------------------------------------------"
   echo "Commit failed! Reason: Commit message does not include issue number or issue number is invalid"
   echo "Correct example: feat: #API-001 Add member list API"
   echo "Commit message: ${MSG}"
   echo "-------------------------------------------------------------------"
   exit 1;
fi

exit 0
