#!/bin/sh

#
#  Go code style automatic review
#
#  Usage: Copy this file to repository directory ".git/hooks"
#

set -e

# Check style for main and test
go fmt .

# Check the exit status
if [ $? -eq 0 ]; then
  echo "Congratulations, code complies with standards!"
else
  echo "Code style review failed, please modify before committing!"
  exit 1
fi