#!/bin/sh

#
#  Go代码规范自动审查
#
#  使用方法: 拷贝此文件到仓库目录".git/hooks"
#

set -e

# Check style for main and test
go fmt .

# Check the exit status
if [ $? -eq 0 ]; then
  echo "恭喜您, 代码符合规范!"
else
  echo "代码规范审查失败, 请修改后再进行提交!"
  exit 1
fi